

entryPoints:
  http:
    address: ":80"
    redirections:
      entryPoints:
        schema: https

  https:
    address: ":443"
    onDefault: true
    http:
      tls:
        certResolver: letsencrypt


accessLog:
  filePath: /var/log/traefik-access.log
log:
  level: INFO
  filePath: /var/log/traefik.log

providers:
  docker:
      endpoint: "unix:///var/run/docker.sock"
      exposedByDefault: false
      network: external

api:
  dashboard: true

certificatesResolvers:
  letsencrypt:
    acme:
      email: am.businessmail.exp@gmail.com
      tlsChallenge: true
      storage: /letsencrypt/acme.json
